import { Itim } from "next/font/google";
import Header from "./_ui/Header";
import "@/app/_styles/globals.css";
import { SkeletonTheme } from "react-loading-skeleton";
import SearchLogout from "./_ui/SearchLogout";
import { UserProvider } from "./_components/UserContext";

const itim = Itim({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});
export const metadata = {
  title: {
    template: "%s | MovieVilla",
    default: "Welcome | MovieVilla",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${itim.className} bg-[#0f0f0f] antialiased w-full flex flex-col relative min-h-screen`}
      >
        <Header>
          <SearchLogout />
        </Header>
        <div className="md:px-8 px-3 mt-20">
          <UserProvider>
            <main className="w-full">{children}</main>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
